Repository i-on-project/core, pull requests merged in 2020-07, with the labels that each got.

#124 Docs: Moved read API docs and added MessageFormat doc for the WriteAPI.
  docs/api/read/calendar-terms.md
  docs/api/read/class-sections.md
  docs/api/read/classes.md
  docs/api/read/courses.md
  docs/api/read/events.md
  docs/api/read/programme.md
  docs/api/read/root.md
  docs/api/read/search.md
  docs/api/write/examples/insertClassSectionEvents.json
  docs/api/write/insertClassSectionEvents.md
  docs/api/write/schemas/insertClassSectionEvents.json
  docs/implementation/access_control/Core_Access_Control_Design.md
  docs/implementation/access_control/Http_Exchanges.md
  docs/implementation/access_control/Intro.md
  docs/implementation/access_control/SQL_Access_Control_Design.md
  docs/implementation/cicd/integration-testing.md
  docs/implementation/read_api/full-text-search/README.md
  docs/implementation/read_api/full-text-search/api.md
  docs/implementation/read_api/full-text-search/how-to.md
  docs/implementation/read_api/full-text-search/implementation.md
  docs/implementation/read_api/full-text-search/indexing.md
  docs/implementation/write_api/insertClassSectionEvents.md
Labels: documentation

#201 Refactor/gh 88 intellij code style
  project/build.gradle.kts
  project/buildSrc/src/main/kotlin/TokenGenerator.kt
  project/buildSrc/src/main/kotlin/db.kt
  project/common_kotlin_code_style.xml
  project/default-detekt-config.yml
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessController.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessServices.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/PDP.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/TokenGenerator.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/entities/ClaimsEntity.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/entities/PolicyEntity.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/entities/TokenEntity.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/sql/AuthRepo.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/sql/AuthRepoData.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/sql/AuthRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/sql/PolicyMapper.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/pap/sql/TokenMapper.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/TokenIssueDetails.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/TokenRepr.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarController.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepo.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/calendar/ICalendarHttpMessageConverter.kt
  project/src/main/kotlin/org/ionproject/core/calendar/category/CategoryData.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/Event.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/properties/MultiValuedProperty.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/types/MultiValue.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/DatatypeMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/SirenDatatypeMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/sql/CalendarTermData.kt
  project/src/main/kotlin/org/ionproject/core/classSection/sql/ClassSectionData.kt
  project/src/main/kotlin/org/ionproject/core/classSection/sql/ClassSectionMapper.kt
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/common/customExceptions/ForeignKeyException.kt
  project/src/main/kotlin/org/ionproject/core/common/interceptors/ControlAccessInterceptor.kt
  project/src/main/kotlin/org/ionproject/core/common/querybuilder/Condition.kt
  project/src/main/kotlin/org/ionproject/core/common/querybuilder/SQLQueryBuilder.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/course/sql/CourseMapper.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassClassSectionMapper.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassData.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassMapper.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassReducedMapper.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeData.kt
Labels: quality of life, refactor

#188 CI using docker compose
  .docker/compose_ci.yaml
  .docker/compose_db.yaml
  .docker/compose_run.yaml
  .docker/src
  .github/workflows/continuous_integration.yaml
  .github/workflows/gcp_release_deploy.yaml
  README.md
  project/res
  project/src/test/resources/bin/poll_db_and_build
  project/src/test/resources/bin/schema_diff/Dockerfile
  project/src/test/resources/bin/schema_diff/sdiff
  project/src/test/resources/docker/sql/strip-privileges.sql
  project/src/test/resources/docker/sql/tokens.sql
  project/src/test/resources/dockerfile_assemble
  project/src/test/resources/dockerfile_ci
  project/src/test/resources/dockerfile_db
Labels: documentation, enhancement

#206 Fixes CI and changes evvar name for the secret key.
  .docker/compose_ci.yaml
  .docker/compose_run.yaml
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessController.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessServices.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/PDP.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/TokenGenerator.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/ImportLinkRepr.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/JWT.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/common/interceptors/ControlAccessInterceptor.kt
  project/src/test/kotlin/org/ionproject/core/accessControl/AccessControlTest.kt
  project/src/test/kotlin/org/ionproject/core/accessControl/ImportLinkTests.kt
  project/src/test/kotlin/org/ionproject/core/utils/ControllerTester.kt
  project/src/test/kotlin/org/ionproject/core/utils/TestBootTokenGeneration.kt
  project/src/test/resources/docker/sql/insert.sql
Labels: enhancement

#207 Feature [Deploy]: Using docker-compose for deploy.
  .docker/.gitignore
  .docker/compose_deploy.yaml
  .github/workflows/gcp_release_deploy.yaml
  project/src/test/resources/bin/deploy
  project/src/test/resources/bin/schema_diff/sdiff
  project/src/test/resources/dockerfile_deploy
Labels: enhancement

#210 [Write API]: Make JSON Schema less restrictive.
  docs/api/write/insertClassSectionEvents.md
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/json/SchemaValidator.kt
Labels: documentation, enhancement

#204 Import link Feature & Docs
  .docker/compose_ci.yaml
  .docker/compose_run.yaml
  README.md
  docs/access_control/Import_Calendars.md
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessController.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessServices.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/PDP.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/TokenGenerator.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/ImportLinkRepr.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/JWT.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/common/interceptors/ControlAccessInterceptor.kt
  project/src/test/kotlin/org/ionproject/core/accessControl/AccessControlTest.kt
  project/src/test/kotlin/org/ionproject/core/accessControl/ImportLinkTests.kt
  project/src/test/kotlin/org/ionproject/core/utils/ControllerTester.kt
  project/src/test/kotlin/org/ionproject/core/utils/TestBootTokenGeneration.kt
  project/src/test/resources/bin/poll_db_and_build
  project/src/test/resources/docker/sql/insert.sql
Labels: documentation, enhancement

#216 Bug - Write API: Transactions now actually are transactions
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsController.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsRepoImpl.kt
Labels: bug

#214 Write API: support recurrent and non recurrent events
  docs/api/write/examples/insertClassSectionEvents.json
  docs/api/write/insertClassSectionEvents.md
  docs/api/write/schemas/insertClassSectionEvents.json
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/json/OperationParams.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/json/SchemaValidator.kt
Labels: enhancement

#222 Feature: Add IDs to requests
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/common/filters/RequestIDFilter.kt
  project/src/main/kotlin/org/ionproject/core/common/interceptors/LoggerInterceptor.kt
Labels: enhancement

#230 Feature: Instants
  project/buildSrc/src/main/kotlin/db.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsController.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/json/OperationParams.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/sql/InsertClassSectionEventsData.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionFaculty/InsertClassSectionFacultyController.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionFaculty/InsertClassSectionFacultyRepo.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionFaculty/InsertClassSectionFacultyServices.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionFaculty/json/OperationParams.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert-testing-data.sql
Labels: enhancement

#240 Bug: Fixed null name in result
  project/src/main/kotlin/org/ionproject/core/course/sql/CourseData.kt
Labels: bug

#252 Bug: Courses with no classes now show up but without current link
  project/src/main/kotlin/org/ionproject/core/course/model/Course.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseCreationRepr.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseListRepr.kt
  project/src/test/kotlin/org/ionproject/core/course/CourseControllerTest.kt
  project/src/test/resources/docker/sql/create-schema.sql
Labels: bug

#251 Bug: v_componentscommon doesn't show invalid events
  project/src/test/resources/docker/sql/create-schema.sql
Labels: bug

#256 Refactor: Programme offer physical model
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/programme/model/ProgrammeOffer.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeOfferCreationRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeOfferDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeData.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeOfferMapper.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeOfferRowReducer.kt
  project/src/test/kotlin/org/ionproject/core/programme/ProgrammeControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/programme/ProgrammeModelTest.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert-testing-data.sql
Labels: refactor
