Repository i-on-project/core, pull requests merged in 2020-03, with the labels that each got.

#7 Docs: Read API Spec - Events
  docs/api/events.md
Labels: documentation

#14 Feature: Project skeleton
  project/.gitignore
  project/build.gradle.kts
  project/gradle/wrapper/gradle-wrapper.jar
  project/gradle/wrapper/gradle-wrapper.properties
  project/gradlew
  project/gradlew.bat
  project/settings.gradle.kts
  project/src/main/kotlin/edu/isel/ion/core/CoreApplication.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSection.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSectionController.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSectionRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSectionService.kt
  project/src/main/kotlin/edu/isel/ion/core/course/Course.kt
  project/src/main/kotlin/edu/isel/ion/core/course/CourseController.kt
  project/src/main/kotlin/edu/isel/ion/core/course/CourseRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/course/CourseService.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/Class.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/ClassController.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/ClassRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/ClassService.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/Programme.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/ProgrammeController.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/ProgrammeRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/ProgrammeService.kt
  project/src/main/resources/application.properties
  project/src/test/kotlin/edu/isel/ion/core/CoreApplicationTests.kt
Labels: enhancement

#15 Bugfix: Changing project groupId
  project/build.gradle.kts
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSection.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSectionController.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSectionRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/class_section/ClassSectionService.kt
  project/src/main/kotlin/edu/isel/ion/core/course/Course.kt
  project/src/main/kotlin/edu/isel/ion/core/course/CourseController.kt
  project/src/main/kotlin/edu/isel/ion/core/course/CourseRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/course/CourseService.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/Class.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/ClassController.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/ClassRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/course_instance/ClassService.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/Programme.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/ProgrammeController.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/ProgrammeRepo.kt
  project/src/main/kotlin/edu/isel/ion/core/programme/ProgrammeService.kt
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSection.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionController.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionRepo.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionService.kt
  project/src/main/kotlin/org/ionproject/core/course/Course.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseController.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseRepo.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseService.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/Class.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassController.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassRepo.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassService.kt
  project/src/main/kotlin/org/ionproject/core/programme/Programme.kt
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeController.kt
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeRepo.kt
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeService.kt
  project/src/test/kotlin/org/ionproject/core/CoreApplicationTests.kt
Labels: bug

#17 Feature/gh 13 class class section model
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSection.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionController.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionRepo.kt
  project/src/main/kotlin/org/ionproject/core/common/siren.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/Class.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassController.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassRepo.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/CourseInstance.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/CourseInstanceController.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/CourseInstanceRepo.kt
Labels: enhancement
