Repository i-on-project/core, pull requests merged in 2020-04, with the labels that each got.

#9 Docs/gh 6 read api spec
  docs/api/calendar-terms.md
  docs/api/class-sections.md
  docs/api/classes.md
  docs/api/courses.md
  docs/api/events.md
  docs/api/root.md
Labels: documentation

#18 Feature/gh 13 project structure creation
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSection.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionController.kt
  project/src/main/kotlin/org/ionproject/core/class_section/ClassSectionRepo.kt
  project/src/main/kotlin/org/ionproject/core/common/siren.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/Class.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassController.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/ClassRepo.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/CourseInstance.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/CourseInstanceController.kt
  project/src/main/kotlin/org/ionproject/core/course_instance/CourseInstanceRepo.kt
Labels: enhancement

#21 Adds JDBI support and PostgreSQL's driver
  project/build.gradle.kts
Labels: enhancement

#34 Adds Json-Home
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/common/Media.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeRepresentation.kt
Labels: enhancement

#41 Removed some composite keys in favor of identity
  sql/create.sql
  sql/drop.sql
  sql/insert.sql
Labels: bug

#45 Feature/gh 30 siren uri templates
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/CalendarTermController.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/representations/CalendarTermDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/representations/CalendarTermListRepr.kt
  project/src/main/kotlin/org/ionproject/core/classSection/representations.kt
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/common/UriTemplatex.kt
  project/src/main/kotlin/org/ionproject/core/common/siren.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseCreationRepr.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseListRepr.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeRepresentation.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassController.kt
  project/src/main/kotlin/org/ionproject/core/klass/representations.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeListRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeOfferDetailRepr.kt
  project/src/test/kotlin/org/ionproject/core/klass/KlassControllerTest.kt
Labels: enhancement

#48 CalendarDataType proposal.
  sql/calendar.sql
  sql/create.sql
  sql/insert.sql
Labels: enhancement

#46 Feature/gh 29 calendar phy model
  sql/calendar.sql
  sql/course_scripts.sql
  sql/create.sql
  sql/drop.sql
  sql/init
  sql/insert.sql
  sql/utils.sql
Labels: enhancement
