Repository i-on-project/core, pull requests merged in 2020-05, with the labels that each got.

#54 Bugfix: Changed CalendarComponent view for better object mapping
  sql/calendar.sql
  sql/insert.sql
Labels: bug

#57 Correcting siren overall
  project/src/main/kotlin/org/ionproject/core/calendarTerm/representations/CalendarTermDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/representations/CalendarTermListRepr.kt
  project/src/main/kotlin/org/ionproject/core/classSection/ClassSectionRepresentations.kt
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/common/siren.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseListRepr.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassRepresentations.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeListRepr.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeOfferDetailRepr.kt
Labels: enhancement

#64 Adds fun entities() to SirenBuilder, for inserting a single embed.
  project/src/main/kotlin/org/ionproject/core/classSection/ClassSectionRepresentations.kt
  project/src/main/kotlin/org/ionproject/core/common/siren.kt
  project/src/main/kotlin/org/ionproject/core/course/representations/CourseDetailRepr.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassRepresentations.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeOfferDetailRepr.kt
Labels: enhancement

#65 Controller unit tests
  project/src/main/kotlin/org/ionproject/core/course/CourseRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassRepresentations.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeListRepr.kt
  project/src/test/kotlin/org/ionproject/core/classSection/ClassSectionControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/classSection/ClassSectionModelTest.kt
  project/src/test/kotlin/org/ionproject/core/course/CourseControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/course/CourseModelTest.kt
  project/src/test/kotlin/org/ionproject/core/klass/KlassControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/klass/KlassModelTest.kt
  project/src/test/kotlin/org/ionproject/core/programme/ProgrammeControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/programme/ProgrammeModelTest.kt
  project/src/test/kotlin/org/ionproject/core/utils.kt
  project/src/test/kotlin/org/ionproject/core/utils/ControllerTester.kt
  project/src/test/kotlin/org/ionproject/core/utils/SirenMvcMatcher.kt
  project/src/test/kotlin/org/ionproject/core/utils/TransactionManagerTest.kt
Labels: test

#67 Change read API according to the amends made in #38
  docs/api/programme.md
Labels: documentation

#69 Fixed root.md's example JSON object.
  docs/api/root.md
Labels: documentation

#75 ProgrammeOffer reduced representation includes the Offer ID as a property
  docs/api/programme.md
  project/src/main/kotlin/org/ionproject/core/programme/representations/ProgrammeDetailRepr.kt
  project/src/test/kotlin/org/ionproject/core/programme/ProgrammeControllerTest.kt
Labels: enhancement

#83 Correction
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarController.kt
  project/src/main/kotlin/org/ionproject/core/common/messageConverters/SirenMessageConverter.kt
Labels: enhancement

#84 Refactor: Use constants in SQL queries.
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarData.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarExt.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepo.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarData.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/CalendarTermRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/sql/CalendarTermData.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/sql/CalendarTermMapper.kt
  project/src/main/kotlin/org/ionproject/core/classSection/ClassSectionMapper.kt
  project/src/main/kotlin/org/ionproject/core/classSection/ClassSectionRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/classSection/sql/ClassSectionData.kt
  project/src/main/kotlin/org/ionproject/core/classSection/sql/ClassSectionMapper.kt
  project/src/main/kotlin/org/ionproject/core/common/customExceptions/UnknownCalendarComponentTypeException.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseMapper.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/course/sql/CourseData.kt
  project/src/main/kotlin/org/ionproject/core/course/sql/CourseMapper.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassClassSectionMapper.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassData.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassMapper.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassReducedMapper.kt
  project/src/main/kotlin/org/ionproject/core/programme/ProgrammeRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeMapper.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeOfferMapper.kt
Labels: refactor

#87 Bug: Duplicate component properties
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
Labels: bug

#91 Bug fix: orders class sections in a class resource's full representation
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassData.kt
  project/src/test/kotlin/org/ionproject/core/klass/KlassControllerTest.kt
Labels: bug

#95 Updated the SQL scripts and adjusted some Repositories
  project/buildSrc/src/main/kotlin/db.kt
  project/src/main/kotlin/org/ionproject/core/classSection/sql/ClassSectionData.kt
  project/src/main/kotlin/org/ionproject/core/course/sql/CourseData.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassData.kt
  project/src/test/resources/sql/create-schema.sql
  project/src/test/resources/sql/insert.sql
  sql/calendar.sql
  sql/create.sql
  sql/drop.sql
  sql/drop_create_insert_script.bat
  sql/init
  sql/insert.sql
  sql/utils.sql
  sql/views.sql
Labels: enhancement

#90 Feature: SQLQuerybuilder
  project/build.gradle.kts
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarController.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepo.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarData.kt
  project/src/main/kotlin/org/ionproject/core/common/querybuilder/Condition.kt
  project/src/main/kotlin/org/ionproject/core/common/querybuilder/SQLQueryBuilder.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
Labels: enhancement

#100 Fixes CalendarData's queries according to the new physical model.
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarData.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/sql/CalendarTermData.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarErrorTest.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarModelTest.kt
  project/src/test/kotlin/org/ionproject/core/calendarTerm/CalendarTermErrorTest.kt
  project/src/test/kotlin/org/ionproject/core/classSection/ClassSectionControllerTest.kt
Labels: bug

#106 Bug: corrected calendar component Siren and some tests errors
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarController.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/utils/ical4jext.kt
  project/src/test/resources/sql/create-schema.sql
  project/src/test/resources/sql/insert.sql
Labels: bug, test

#109 Feature/gh 51 improve tasks
  project/build.gradle.kts
  project/buildSrc/src/main/kotlin/db.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert.sql
Labels: enhancement

#107 Feature/gh 93 insert more db data
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarExt.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/types/Text.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarData.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarErrorTest.kt
  project/src/test/kotlin/org/ionproject/core/utils/ical4jext.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert.sql
Labels: enhancement

#111 Fixes docker port mapping.
  project/build.gradle.kts
  project/buildSrc/src/main/kotlin/db.kt
Labels: bug

#98 Bugfix: calendar read API corrections
  docs/api/events.md
Labels: bug, documentation

#116 JsonHome's ResourceBuilder refactor and HomeDocumentTest added.
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeRepresentation.kt
  project/src/test/kotlin/org/ionproject/core/home/HomeDocumentTest.kt
Labels: refactor

#114 Fix: Comma escaping now only in iCalendar
  project/src/main/kotlin/org/ionproject/core/calendar/ICalendarHttpMessageConverter.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/types/Text.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
  project/src/main/kotlin/org/ionproject/core/kotlinx.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/resources/docker/sql/insert.sql
Labels: bug

#131 Creates Drop Schema SQL script
  project/src/test/resources/docker/sql/drop-schema.sql
Labels: enhancement
