Repository i-on-project/core, pull requests merged in 2020-06, with the labels that each got.

#77 Document describing the different integration testing options.
  docs/implementation/integration-testing.md
Labels: documentation

#135 Fix Docs: Rel fixes
  docs/api/search.md
  docs/full-text-search/implementation.md
Labels: bug, documentation

#138 Bug: Removed tests with Strings
  project/src/test/kotlin/org/ionproject/core/home/HomeDocumentTest.kt
  project/src/test/kotlin/org/ionproject/core/home/HomeTestModel.kt
Labels: bug, test

#142 Docs Fix: Search result entites id type and class
  docs/api/search.md
Labels: bug, documentation

#146 Fixes Lecture category of various insert.sql statements.
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/resources/docker/sql/insert.sql
Labels: bug

#133 Adds workflow files for CD.
  .github/workflows/continuous_integration.yaml
  .github/workflows/gcp_release_deploy.yaml
  project/.dockerignore
  project/Dockerfile
  project/build.gradle.kts
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/schema_diff/Dockerfile
  project/src/test/resources/schema_diff/sdiff
Labels: enhancement

#147 Docs: Readme with a more verbose guide
  README.md
Labels: documentation

#155 Adds search resource to the home doc
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/test/kotlin/org/ionproject/core/home/HomeDocumentTest.kt
Labels: enhancement

#140 Feature: Kotlin and SQL Full-Text Search implementation
  project/src/main/kotlin/org/ionproject/core/CoreApplication.kt
  project/src/main/kotlin/org/ionproject/core/calendar/CalendarController.kt
  project/src/main/kotlin/org/ionproject/core/calendar/ICalendarHttpMessageConverter.kt
  project/src/main/kotlin/org/ionproject/core/calendarTerm/sql/CalendarTermData.kt
  project/src/main/kotlin/org/ionproject/core/classSection/sql/ClassSectionData.kt
  project/src/main/kotlin/org/ionproject/core/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/common/transaction/DataSourceHolder.kt
  project/src/main/kotlin/org/ionproject/core/common/transaction/SQLErrors.kt
  project/src/main/kotlin/org/ionproject/core/common/transaction/SqlLogger.kt
  project/src/main/kotlin/org/ionproject/core/common/transaction/TransactionManagerImpl.kt
  project/src/main/kotlin/org/ionproject/core/course/CourseRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/course/sql/CourseData.kt
  project/src/main/kotlin/org/ionproject/core/home/JsonHomeController.kt
  project/src/main/kotlin/org/ionproject/core/klass/KlassRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassData.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassMapper.kt
  project/src/main/kotlin/org/ionproject/core/klass/sql/KlassReducedMapper.kt
  project/src/main/kotlin/org/ionproject/core/programme/sql/ProgrammeData.kt
  project/src/main/kotlin/org/ionproject/core/search/SearchController.kt
  project/src/main/kotlin/org/ionproject/core/search/SearchRepo.kt
  project/src/main/kotlin/org/ionproject/core/search/SearchRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/search/model/SearchQuery.kt
  project/src/main/kotlin/org/ionproject/core/search/model/SearchResult.kt
  project/src/main/kotlin/org/ionproject/core/search/model/SearchResultCollection.kt
  project/src/main/kotlin/org/ionproject/core/search/representations/SearchResultListRepr.kt
  project/src/main/kotlin/org/ionproject/core/search/sql/SearchData.kt
  project/src/main/kotlin/org/ionproject/core/search/sql/SearchResultMapper.kt
  project/src/test/kotlin/org/ionproject/core/home/HomeDocumentTest.kt
  project/src/test/kotlin/org/ionproject/core/search/ClassSearchControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/search/CourseSearchControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/search/SearchControllerTest.kt
  project/src/test/kotlin/org/ionproject/core/search/SearchErrorTest.kt
  project/src/test/kotlin/org/ionproject/core/search/SearchModelTest.kt
  project/src/test/kotlin/org/ionproject/core/search/SearchSirenTest.kt
  project/src/test/kotlin/org/ionproject/core/utils/sirenext.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert.sql
Labels: enhancement

#153 Bug: Siren date format
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/types/Date.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/types/DateTime.kt
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/types/Time.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/DatatypeMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/SirenDatatypeMapper.kt
Labels: bug

#160 Docs: Adds a readme guide for access token use.
  README.md
Labels: documentation

#159 Bug/gh 158 psql remotely
  .github/workflows/gcp_release_deploy.yaml
  project/buildSrc/src/main/kotlin/db.kt
Labels: bug

#161 Bug: Recur(iCalendar recurrency type) dates.
  project/build.gradle.kts
  project/buildSrc/src/main/kotlin/db.kt
  project/src/main/kotlin/org/ionproject/core/calendar/representations/SirenDatatypeMapper.kt
Labels: bug

#157 Docs: Search Errors
  docs/api/search.md
Labels: documentation

#168 changes
  docs/access_control/Http_Exchanges.md
  project/src/main/kotlin/org/ionproject/core/accessControl/AccessController.kt
  project/src/main/kotlin/org/ionproject/core/accessControl/representations/TokenRevokedRepr.kt
  project/src/test/kotlin/org/ionproject/core/accessControl/AccessControlTest.kt
Labels: documentation, enhancement

#174 Bug: Fixed problem with one word strings in composite type
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
Labels: bug

#177 Fixed templating
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
Labels: bug

#175 Refactor: Removed internationalization from the model
  project/src/main/kotlin/org/ionproject/core/calendar/category/CategoryData.kt
  project/src/main/kotlin/org/ionproject/core/calendar/category/CategoryRepo.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert.sql
Labels: refactor

#179 Feature: Added Location property to Event
  project/src/main/kotlin/org/ionproject/core/calendar/icalendar/Event.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarComponentMapper.kt
  project/src/main/kotlin/org/ionproject/core/calendar/sql/CalendarData.kt
  project/src/test/kotlin/org/ionproject/core/calendar/CalendarControllerTest.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert.sql
Labels: enhancement

#181 Fix: PS is now mandatory and CC optional
  project/src/test/resources/docker/sql/insert.sql
Labels: bug

#186 Uses an auxiliary script for token insertion.
  project/build.gradle.kts
  project/buildSrc/build.gradle.kts
  project/buildSrc/src/main/kotlin/db.kt
Labels: bug

#185 Fix: Calendar Siren on repeating properties
  project/src/main/kotlin/org/ionproject/core/calendar/representations/CalendarSirenRepr.kt
Labels: bug

#191 ExceptionHandling+ProblemJSON responses enhanced.
  project/src/main/kotlin/org/ionproject/core/common/ExceptionHandler.kt
Labels: bug

#182 Feature [Write API]: Insert Class Section Events Operation
  project/build.gradle.kts
  project/src/main/kotlin/org/ionproject/core/writeApi/common/Uri.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsController.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsRepo.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsRepoImpl.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/InsertClassSectionEventsServices.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/json/OperationParams.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/json/SchemaValidator.kt
  project/src/main/kotlin/org/ionproject/core/writeApi/insertClassSectionEvents/sql/InsertClassSectionEventsData.kt
  project/src/test/resources/docker/sql/create-schema.sql
  project/src/test/resources/docker/sql/insert.sql
Labels: enhancement

#194 Feature: Date Format exception handling
  docs/api/events.md
  project/src/main/kotlin/org/ionproject/core/common/ExceptionHandler.kt
Labels: documentation, enhancement
